/*
 * Download SQL Server from the web (from www.microsoft.com) and install on machine.
 * Then:
 *    1) Download data into some directory on the machine
 *    2) Open SQL Server Management Studio
 *    3) Set @LOADDIR in this script to the directory where you downloaded the files
 */

USE SQLBook

DECLARE @LOADDIR VARCHAR(255) = 'C:\Users\solan\OneDrive\Desktop\St.Clair\Sem_2\203';
DECLARE @SQL NVARCHAR(MAX);


CREATE TABLE  Subscribers (
  SubscriberId int NOT NULL primary key,
  RatePlan varchar(6) NOT NULL,
  MonthlyFee float NOT NULL,
  Market varchar(10) NOT NULL,
  Channel varchar(6) NOT NULL,
  StartDate varchar(255),
  StopDate varchar(255),
  StopType char(4),
  Tenure varchar(255),
  IsActive int default NULL
);

SET @SQL = '
BULK INSERT SQLBook..Subscribers
    FROM ''@LOADDIR\subscribers.txt''
	WITH (FIRSTROW = 2, FIELDTERMINATOR = ''	'')
';

SET @SQL = REPLACE(@SQL, '@LOADDIR', @LOADDIR)

EXEC(@SQL);

UPDATE SQLBook..Subscribers
    SET StopDate = NULL, StopType = NULL
	WHERE StopDate = 'NULL';

UPDATE SQLBook..Subscribers
    SET StartDate = NULL
	WHERE StartDate = 'NULL';

UPDATE SQLBook..Subscribers
    SET tenure = NULL
	WHERE tenure = 'NULL';

ALTER TABLE SQLBook..Subscribers ALTER COLUMN StartDate date;
ALTER TABLE SQLBook..Subscribers ALTER COLUMN StopDate date;
ALTER TABLE SQLBook..Subscribers ALTER COLUMN StopType char(1);
ALTER TABLE SQLBook..Subscribers ALTER COLUMN Tenure int;



CREATE TABLE ZipCounty (
    ZipCode char(5),
	Latitude decimal(18, 6),
	Longitude decimal(18, 6), 
	POName varchar(255), 
    ZipClass varchar(255),
	CountyFIPS varchar(255),
	State varchar(2),
	CountyName varchar(255),
	CountyPop int,
	Countyhu int,
	CountyLandAreaMiles float,
	CountyWaterAreaMiles float
) ;

SET @SQL = '
BULK INSERT SQLBook..ZipCounty
    FROM ''@LOADDIR\ZipCounty.txt''
	WITH (FIRSTROW = 2, FIELDTERMINATOR = ''	'')
';

SET @SQL = REPLACE(@SQL, '@LOADDIR', @LOADDIR)

EXEC(@SQL);



CREATE TABLE ZipCensus (
	state varchar(255) NULL,
	zcta5 varchar(255) NULL,
	ZIPName varchar(255) NULL,
	County varchar(255) NULL,
	pctcnty decimal(6, 4) NULL,
	Fipco int NULL,
	FipCo2 int NULL,
	pctState decimal(6, 4) NULL,
	AltZIPs varchar(255) NULL,
	NaltZIPs int NULL,
	Stab varchar(255) NULL,
	Latitude float NULL,
	Longitude float NULL,
	LandSQMI float NULL,
	AreaSQMI float NULL,
	TotPopsf1 int NULL,
	esriid int NULL,
	geoid varchar(255) NULL,
	AreaName varchar(255) NULL,
	LogRecno int NULL,
	TotPop int NULL,
	Age0_4 int NULL,
	pctAge0_4 decimal(6, 4) NULL,
	Age5_9 int NULL,
	pctAge5_9 decimal(6, 4) NULL,
	Age10_14 int NULL,
	pctAge10_14 decimal(6, 4) NULL,
	Age15_19 int NULL,
	pctAge15_19 decimal(6, 4) NULL,
	Age20_24 int NULL,
	pctAge20_24 decimal(6, 4) NULL,
	Age25_34 int NULL,
	pctAge25_34 decimal(6, 4) NULL,
	Age35_44 int NULL,
	pctAge35_44 decimal(6, 4) NULL,
	Age45_54 int NULL,
	pctAge45_54 decimal(6, 4) NULL,
	Age55_59 int NULL,
	pctAge55_59 decimal(6, 4) NULL,
	Age60_64 int NULL,
	pctAge60_64 decimal(6, 4) NULL,
	Age65_74 int NULL,
	pctAge65_74 decimal(6, 4) NULL,
	Age75_84 int NULL,
	pctAge75_84 decimal(6, 4) NULL,
	Over85 int NULL,
	pctOver85 decimal(6, 4) NULL,
	MedianAge float NULL,
	Over5 int NULL,
	pctOver5 decimal(6, 4) NULL,
	Over15 int NULL,
	pctOver15 decimal(6, 4) NULL,
	Under18 int NULL,
	pctUnder18 decimal(6, 4) NULL,
	Over18 int NULL,
	pctOver18 decimal(6, 4) NULL,
	Over21 int NULL,
	pctOver21 decimal(6, 4) NULL,
	Over25 int NULL,
	pctOver25 decimal(6, 4) NULL,
	Over62 int NULL,
	pctOver62 decimal(6, 4) NULL,
	Over65 int NULL,
	pctOver65 decimal(6, 4) NULL,
	Males int NULL,
	pctMales decimal(6, 4) NULL,
	Over18Males int NULL,
	pctOver18Males decimal(6, 4) NULL,
	Over65Males int NULL,
	pctOver65Males decimal(6, 4) NULL,
	Females int NULL,
	pctFemales decimal(6, 4) NULL,
	Over18Females int NULL,
	pctOver18Females decimal(6, 4) NULL,
	Over65Females int NULL,
	pctOver65Females decimal(6, 4) NULL,
	OneRace int NULL,
	pctOneRace decimal(6, 4) NULL,
	White1 int NULL,
	pctWhite1 decimal(6, 4) NULL,
	Black1 int NULL,
	pctBlack1 decimal(6, 4) NULL,
	Indian1 int NULL,
	pctIndian1 decimal(6, 4) NULL,
	Asian1 int NULL,
	pctAsian1 decimal(6, 4) NULL,
	HawnPI1 int NULL,
	pctHawnPI1 decimal(6, 4) NULL,
	Other1 int NULL,
	pctOther1 decimal(6, 4) NULL,
	MultiRace int NULL,
	pctMultiRace decimal(6, 4) NULL,
	White2 int NULL,
	pctWhite2 decimal(6, 4) NULL,
	Black2 int NULL,
	pctBlack2 decimal(6, 4) NULL,
	Indian2 int NULL,
	pctIndian2 decimal(6, 4) NULL,
	Asian2 int NULL,
	pctAsian2 decimal(6, 4) NULL,
	HawnPI2 int NULL,
	pctHawnPI2 decimal(6, 4) NULL,
	Other2 int NULL,
	pctOther2 decimal(6, 4) NULL,
	HispanicPop int NULL,
	pctHispanicPop decimal(6, 4) NULL,
	NonHispPop int NULL,
	pctNonHispPop decimal(6, 4) NULL,
	NonHispWhite int NULL,
	pctNonHispWhite decimal(6, 4) NULL,
	NonHispBlack int NULL,
	pctNonHispBlack decimal(6, 4) NULL,
	NonHispAmInd int NULL,
	pctNonHispAmInd decimal(6, 4) NULL,
	NonHispAsian int NULL,
	pctNonHispAsian decimal(6, 4) NULL,
	NonHispHawnPI int NULL,
	pctNonHispHawnPI decimal(6, 4) NULL,
	TotHHs int NULL,
	HHInc0 int NULL,
	pctHHInc0 decimal(6, 4) NULL,
	HHInc10 int NULL,
	pctHHInc10 decimal(6, 4) NULL,
	HHInc15 int NULL,
	pctHHInc15 decimal(6, 4) NULL,
	HHInc25 int NULL,
	pctHHInc25 decimal(6, 4) NULL,
	HHInc35 int NULL,
	pctHHInc35 decimal(6, 4) NULL,
	HHInc50 int NULL,
	pctHHInc50 decimal(6, 4) NULL,
	HHInc75 int NULL,
	pctHHInc75 decimal(6, 4) NULL,
	HHInc100 int NULL,
	pctHHInc100 decimal(6, 4) NULL,
	HHInc150 int NULL,
	pctHHInc150 decimal(6, 4) NULL,
	HHInc200 int NULL,
	pctHHInc200 decimal(6, 4) NULL,
	MedianHHInc money NULL,
	AvgHHInc money NULL,
	NumHHEarnings int NULL,
	pctNumHHEarnings decimal(6, 4) NULL,
	AvgHHEarnings money NULL,
	NumHHSocSec int NULL,
	pctNumHHSocSec decimal(6, 4) NULL,
	AvgHHSocSec money NULL,
	NumHHRetInc int NULL,
	pctNumHHRetInc decimal(6, 4) NULL,
	AvgHHRetInc money NULL,
	NumHHSuppSecInc int NULL,
	pctNumHHSuppSecInc decimal(6, 4) NULL,
	AvgHHSuppSecInc money NULL,
	NumHHPubAssist int NULL,
	pctNumHHPubAssist decimal(6, 4) NULL,
	AvgHHPubAssist money NULL,
	NumHHFoodStmp int NULL,
	pctNumHHFoodStmp decimal(6, 4) NULL,
	FamHHs int NULL,
	pctFamHHs decimal(6, 4) NULL,
	FamHHInc0 int NULL,
	pctFamHHInc0 decimal(6, 4) NULL,
	FamHHInc10 int NULL,
	pctFamHHInc10 decimal(6, 4) NULL,
	FamHHInc15 int NULL,
	pctFamHHInc15 decimal(6, 4) NULL,
	FamHHInc25 int NULL,
	pctFamHHInc25 decimal(6, 4) NULL,
	FamHHInc35 int NULL,
	pctFamHHInc35 decimal(6, 4) NULL,
	FamHHInc50 int NULL,
	pctFamHHInc50 decimal(6, 4) NULL,
	FamHHInc75 int NULL,
	pctFamHHInc75 decimal(6, 4) NULL,
	FamHHInc100 int NULL,
	pctFamHHInc100 decimal(6, 4) NULL,
	FamHHInc150 int NULL,
	pctFamHHInc150 decimal(6, 4) NULL,
	FamHHInc200 int NULL,
	pctFamHHInc200 decimal(6, 4) NULL,
	MedianFamInc money NULL,
	AvgFamInc money NULL,
	PCI money NULL,
	NonFamHHs int NULL,
	pctNonFamHHs decimal(6, 4) NULL,
	MedianNonFamInc money NULL,
	AvgNonFamInc money NULL,
	FullTimeWorkers int NULL,
	FullTimeWorkersMale int NULL,
	pctFullTimeWorkersMale decimal(6, 4) NULL,
	FullTimeWorkersFemale int NULL,
	pctFullTimeWorkersFemale decimal(6, 4) NULL,
	MedianEarnings money NULL,
	MedianEarningsMale money NULL,
	MedianEarningsFemale money NULL,
	PovUniverse int NULL,
	Poor int NULL,
	pctPoor decimal(6, 4) NULL,
	PovUniverseUnder18 int NULL,
	PoorUnder18 int NULL,
	PctPoorUnder18 decimal(6, 4) NULL,
	PovUniverse18_64 int NULL,
	Poor18to64 int NULL,
	pctPoor18to64 decimal(6, 4) NULL,
	PovUniverseOver65 int NULL,
	PoorOver65 int NULL,
	pctPoorOver65 decimal(6, 4) NULL,
	PovUniverseFamilyPop int NULL,
	pctFamilyPopPoor decimal(6, 4) NULL,
	PovUniverseUnrelated int NULL,
	PoorInFamily int NULL,
	pctPoorInFamily decimal(6, 4) NULL,
	PoorUnrelated int NULL,
	pctPoorUnrelated decimal(6, 4) NULL,
	PovRatioUnderHalf int NULL,
	pctPovRatioUnderHalf decimal(6, 4) NULL,
	PovRatiov5tov99 int NULL,
	pctPovRatiov5tov99 decimal(6, 4) NULL,
	PovRatio1to2 int NULL,
	pctPovRatio1to2 decimal(6, 4) NULL,
	PovRatioOver2 int NULL,
	pctPovRatioOver2 decimal(6, 4) NULL,
	Over16 int NULL,
	LaborForce int NULL,
	pctLaborForce decimal(6, 4) NULL,
	CivLabForce int NULL,
	pctCivLabForce decimal(6, 4) NULL,
	EmployedCLF int NULL,
	pctEmployedCLF decimal(6, 4) NULL,
	UnemployedCLF int NULL,
	pctUnemployedCLF decimal(6, 4) NULL,
	Military int NULL,
	pctMilitary decimal(6, 4) NULL,
	NotInLF int NULL,
	pctNotInLF decimal(6, 4) NULL,
	Over16Females int NULL,
	pctOver16Females decimal(6, 4) NULL,
	LaborForceFemales int NULL,
	pctLaborForceFemales decimal(6, 4) NULL,
	CivLabForceFemales int NULL,
	pctCivLabForceFemales decimal(6, 4) NULL,
	EmployedFemales int NULL,
	pctEmployedFemales decimal(6, 4) NULL,
	OwnKidsUnder6 int NULL,
	OwnKidsU6AllPrntsWk int NULL,
	pctOwnKidsU6AllPrntsWk decimal(6, 4) NULL,
	OwnKidsOver6 int NULL,
	OwnKidsO6AllPrntsWk int NULL,
	pctOwnKidsO6AllPrntsWk decimal(6, 4) NULL,
	Worker16 int NULL,
	Commuters int NULL,
	pctCommuters decimal(6, 4) NULL,
	DriveAlone int NULL,
	pctDriveAlone decimal(6, 4) NULL,
	Carpool int NULL,
	pctCarpool decimal(6, 4) NULL,
	PublicTrans int NULL,
	pctPublicTrans decimal(6, 4) NULL,
	WalkToWork int NULL,
	pctWalkToWork decimal(6, 4) NULL,
	OtherCommute int NULL,
	pctOtherCommute decimal(6, 4) NULL,
	WorkAtHome int NULL,
	pctWorkAtHome decimal(6, 4) NULL,
	AvgCommute float NULL,
	ManProfOccs int NULL,
	pctManProfOccs decimal(6, 4) NULL,
	ServiceOccs int NULL,
	pctServiceOccs decimal(6, 4) NULL,
	SalesOffOccs int NULL,
	pctSalesOffOccs decimal(6, 4) NULL,
	FarmFishOccs int NULL,
	pctFarmFishOccs decimal(6, 4) NULL,
	ConsOccs int NULL,
	pctConsOccs decimal(6, 4) NULL,
	TransOccs int NULL,
	pctTransOccs decimal(6, 4) NULL,
	Agriculture int NULL,
	pctAgriculture decimal(6, 4) NULL,
	Construction int NULL,
	pctConstruction decimal(6, 4) NULL,
	Manufacturing int NULL,
	pctManufacturing decimal(6, 4) NULL,
	WholesaleTrade int NULL,
	pctWholesaleTrade decimal(6, 4) NULL,
	RetailTrade int NULL,
	pctRetailTrade decimal(6, 4) NULL,
	Transportation int NULL,
	pctTransportation decimal(6, 4) NULL,
	Information int NULL,
	pctInformation decimal(6, 4) NULL,
	Finance_Ins int NULL,
	pctFinance_Ins decimal(6, 4) NULL,
	Professional int NULL,
	pctProfessional decimal(6, 4) NULL,
	Educ_Health_SocSvcs int NULL,
	pctEduc_Health_SocSvcs decimal(6, 4) NULL,
	RecreationEtc int NULL,
	pctRecreationEtc decimal(6, 4) NULL,
	OtherIndustries int NULL,
	pctOtherIndustries decimal(6, 4) NULL,
	PublicAdmin int NULL,
	pctPublicAdmin decimal(6, 4) NULL,
	PrivWageWorkers int NULL,
	pctPrivWageWorkers decimal(6, 4) NULL,
	GovWorkers int NULL,
	pctGovWorkers decimal(6, 4) NULL,
	SelfEmpWorkers int NULL,
	pctSelfEmpWorkers decimal(6, 4) NULL,
	UnpaidFamWorkers int NULL,
	pctUnpaidFamWorkers decimal(6, 4) NULL,
	Families int NULL,
	pctFamilies decimal(6, 4) NULL,
	FamsWithKids int NULL,
	pctFamsWithKids decimal(6, 4) NULL,
	MarriedCouples int NULL,
	pctMarriedCouples decimal(6, 4) NULL,
	CouplesWithKids int NULL,
	pctCouplesWithKids decimal(6, 4) NULL,
	SingleMaleFamilies int NULL,
	pctSingleMaleFamilies decimal(6, 4) NULL,
	SingleFathers int NULL,
	pctSingleFathers decimal(6, 4) NULL,
	SingleFemaleFamilies int NULL,
	pctSingleFemaleFamilies decimal(6, 4) NULL,
	SingleMothers int NULL,
	pctSingleMothers decimal(6, 4) NULL,
	LivingAlone int NULL,
	pctLivingAlone decimal(6, 4) NULL,
	Over65Alone int NULL,
	pctOver65Alone decimal(6, 4) NULL,
	HHsWithKids int NULL,
	pctHHsWithKids decimal(6, 4) NULL,
	HHsWithElders int NULL,
	pctHHsWithElders decimal(6, 4) NULL,
	AvgHHSize float NULL,
	AvgFamSize float NULL,
	HHPop int NULL,
	pctHHPop decimal(6, 4) NULL,
	FamHHpop int NULL,
	pctFamHHpop decimal(6, 4) NULL,
	NonFamHHpop int NULL,
	pctNonFamHHpop decimal(6, 4) NULL,
	GrpQuarters int NULL,
	pctGrpQuarters decimal(6, 4) NULL,
	Householder int NULL,
	pctHouseholder decimal(6, 4) NULL,
	Spouse int NULL,
	pctSpouse decimal(6, 4) NULL,
	Child int NULL,
	pctChild decimal(6, 4) NULL,
	OtherRelative int NULL,
	pctOtherRelative decimal(6, 4) NULL,
	NonRelative int NULL,
	pctNonRelative decimal(6, 4) NULL,
	UnmarriedPartner int NULL,
	pctUnmarriedPartner decimal(6, 4) NULL,
	UMPartnerHHsPerK int NULL,
	NeverMarried int NULL,
	pctNeverMarried decimal(6, 4) NULL,
	Married int NULL,
	pctMarried decimal(6, 4) NULL,
	Separated int NULL,
	pctSeparated decimal(6, 4) NULL,
	Widowed int NULL,
	pctWidowed decimal(6, 4) NULL,
	Divorced int NULL,
	pctDivorced decimal(6, 4) NULL,
	Women15to50 int NULL,
	UnmarriedWomen15to50 int NULL,
	pctUnmarriedWomen15to50 decimal(6, 4) NULL,
	WomenGivingBirth int NULL,
	pctWomenGivingBirth decimal(6, 4) NULL,
	UnmarriedGivingBirth int NULL,
	pctUnmarriedGivingBirth decimal(6, 4) NULL,
	Women15to19 int NULL,
	pctWomen15to19 decimal(6, 4) NULL,
	Women20to34 int NULL,
	pctWomen20to34 decimal(6, 4) NULL,
	Women35to50 int NULL,
	pctWomen35to50 decimal(6, 4) NULL,
	UnmarriedGivingBirthPerk int NULL,
	GivingBirthPerk int NULL,
	BirthRate15_19 int NULL,
	BirthRate20_34 int NULL,
	BirthRate35_50 int NULL,
	GrandPrntsLvngWithGrndkid int NULL,
	GrandPrntsCaring int NULL,
	pctGrandPrntsCaring decimal(6, 4) NULL,
	GrandPrntsCaringLT1 int NULL,
	pctGrandPrntsCaringLT1 decimal(6, 4) NULL,
	GrandPrntsCaring1or2 int NULL,
	pctGrandPrntsCaring1or2 decimal(6, 4) NULL,
	GrandPrntsCaring3or4 int NULL,
	pctGrandPrntsCaring3or4 decimal(6, 4) NULL,
	GrandPrntsCaring5orMore int NULL,
	pctGrandPrntsCaring5orMore decimal(6, 4) NULL,
	Over3 int NULL,
	EnrolledOver3 int NULL,
	pctEnrolledOver3 decimal(6, 4) NULL,
	InNursery int NULL,
	pctInNursery decimal(6, 4) NULL,
	InKindergarten int NULL,
	pctInKindergarten decimal(6, 4) NULL,
	InElementary int NULL,
	pctInElementary decimal(6, 4) NULL,
	InHighSchool int NULL,
	pctInHighSchool decimal(6, 4) NULL,
	InCollege int NULL,
	pctInCollege decimal(6, 4) NULL,
	LessThan9th int NULL,
	pctLessThan9th decimal(6, 4) NULL,
	SomeHighSchool int NULL,
	pctSomeHighSchool decimal(6, 4) NULL,
	HighSchool int NULL,
	pctHighSchool decimal(6, 4) NULL,
	SomeCollege int NULL,
	pctSomeCollege decimal(6, 4) NULL,
	Associates int NULL,
	pctAssociates decimal(6, 4) NULL,
	Bachelors int NULL,
	pctBachelors decimal(6, 4) NULL,
	GradProf int NULL,
	pctGradProf decimal(6, 4) NULL,
	HighSchoolOrMore int NULL,
	pctHighSchoolOrMore decimal(6, 4) NULL,
	Bachelorsormore int NULL,
	pctBachelorsormore decimal(6, 4) NULL,
	Civilian int NULL,
	pctCivilian decimal(6, 4) NULL,
	Veteran int NULL,
	pctVeteran decimal(6, 4) NULL,
	TotPopNonInst int NULL,
	Disabled int NULL,
	pctDisabled decimal(6, 4) NULL,
	NonInstUnder18 int NULL,
	pctNonInstUnder18 decimal(6, 4) NULL,
	DisabledUnder18 int NULL,
	pctDisabledUnder18 decimal(6, 4) NULL,
	NonInst18_64 int NULL,
	pctNonInst18_64 decimal(6, 4) NULL,
	Disabled18_64 int NULL,
	pctDisabled18_64 decimal(6, 4) NULL,
	NonInstOver65 int NULL,
	pctNonInstOver65 decimal(6, 4) NULL,
	DisabledElder int NULL,
	pctDisabledElder decimal(6, 4) NULL,
	Over1 int NULL,
	SameHouse int NULL,
	pctSameHouse decimal(6, 4) NULL,
	DiffHouse int NULL,
	pctDiffHouse decimal(6, 4) NULL,
	DiffHouseSameCounty int NULL,
	pctDiffHouseSameCounty decimal(6, 4) NULL,
	DiffCounty int NULL,
	pctDiffCounty decimal(6, 4) NULL,
	DiffCntySameState int NULL,
	pctDiffCntySameState decimal(6, 4) NULL,
	DiffState int NULL,
	pctDiffState decimal(6, 4) NULL,
	LivedAbroad int NULL,
	pctLivedAbroad decimal(6, 4) NULL,
	USNative int NULL,
	pctUSNative decimal(6, 4) NULL,
	BornInUS int NULL,
	pctBornInUS decimal(6, 4) NULL,
	BornInCurrState int NULL,
	pctBornInCurrState decimal(6, 4) NULL,
	BornInDiffState int NULL,
	pctBornInDiffState decimal(6, 4) NULL,
	BornAbroad int NULL,
	pctBornAbroad decimal(6, 4) NULL,
	ForeignBorn int NULL,
	pctForeignBorn decimal(6, 4) NULL,
	Naturalized int NULL,
	pctNaturalized decimal(6, 4) NULL,
	NonCitizen int NULL,
	pctNonCitizen decimal(6, 4) NULL,
	BornOutsideUS int NULL,
	pctBornOutsideUS decimal(6, 4) NULL,
	BornOutsideUSNative int NULL,
	pctBornOutsideUSNative decimal(6, 4) NULL,
	NativeEnteredGE2000 int NULL,
	pctNativeEnteredGE2000 decimal(6, 4) NULL,
	NativeEnteredLT2000 int NULL,
	pctNativeEnteredLT2000 decimal(6, 4) NULL,
	FBEnteredGE2000 int NULL,
	pctFBEnteredGE2000 decimal(6, 4) NULL,
	FBEnteredLT2000 int NULL,
	pctFBEnteredLT2000 decimal(6, 4) NULL,
	FBMinusSea int NULL,
	pctFBMinusSea decimal(6, 4) NULL,
	FBEurope int NULL,
	pctFBEurope decimal(6, 4) NULL,
	FBAsia int NULL,
	pctFBAsia decimal(6, 4) NULL,
	FBAfrica int NULL,
	pctFBAfrica decimal(6, 4) NULL,
	FBOceania int NULL,
	pctFBOceania decimal(6, 4) NULL,
	FBLatinAmerica int NULL,
	pctFBLatinAmerica decimal(6, 4) NULL,
	FBNorthAmerica int NULL,
	pctFBNorthAmerica decimal(6, 4) NULL,
	EnglishOnly int NULL,
	pctEnglishOnly decimal(6, 4) NULL,
	OthLang int NULL,
	pctOthLang decimal(6, 4) NULL,
	OthLangEnglishLTD int NULL,
	pctOthLangEnglishLTD decimal(6, 4) NULL,
	Spanish int NULL,
	pctSpanish decimal(6, 4) NULL,
	SpanishEnglishLTD int NULL,
	pctSpanishEnglishLTD decimal(6, 4) NULL,
	TotHUs int NULL,
	OccHUs int NULL,
	pctOccHUs decimal(6, 4) NULL,
	OwnerOcc int NULL,
	pctOwnerOcc decimal(6, 4) NULL,
	RenterOcc int NULL,
	pctRenterOcc decimal(6, 4) NULL,
	AvgOwnerHHSize float NULL,
	AvgRenterHHSize float NULL,
	VacHUs int NULL,
	pctVacHUs decimal(6, 4) NULL,
	VacantForSale int NULL,
	pctVacantForSale decimal(6, 4) NULL,
	VacantForRent int NULL,
	pctVacantForRent decimal(6, 4) NULL,
	VacantSeasonal int NULL,
	pctVacantSeasonal decimal(6, 4) NULL,
	TotalOwnerUnits int NULL,
	OwnerVacRate float NULL,
	TotalRentalUnits int NULL,
	RenterVacRate float NULL,
	PersonsInOwnerUnits int NULL,
	pctPersonsInOwnerUnits decimal(6, 4) NULL,
	PersonsInRenterUnits int NULL,
	pctPersonsInRenterUnits decimal(6, 4) NULL,
	Units1 int NULL,
	pctUnits1 decimal(6, 4) NULL,
	Units1Detached int NULL,
	pctUnits1Detached decimal(6, 4) NULL,
	Units1Attached int NULL,
	pctUnits1Attached decimal(6, 4) NULL,
	Units2 int NULL,
	pctUnits2 decimal(6, 4) NULL,
	Units3_4 int NULL,
	pctUnits3_4 decimal(6, 4) NULL,
	Units5_9 int NULL,
	pctUnits5_9 decimal(6, 4) NULL,
	Units10_19 int NULL,
	pctUnits10_19 decimal(6, 4) NULL,
	Units20up int NULL,
	pctUnits20up decimal(6, 4) NULL,
	MobileHomes int NULL,
	pctMobileHomes decimal(6, 4) NULL,
	BoatRV int NULL,
	pctBoatRV decimal(6, 4) NULL,
	MobileHomesPerK int NULL,
	Built2010orLater int NULL,
	pctBuilt2010orLater decimal(6, 4) NULL,
	Built2000_2009 int NULL,
	pctBuilt2000_2009 decimal(6, 4) NULL,
	Built1990_1999 int NULL,
	pctBuilt1990_1999 decimal(6, 4) NULL,
	Built1980_1989 int NULL,
	pctBuilt1980_1989 decimal(6, 4) NULL,
	Built1970_1979 int NULL,
	pctBuilt1970_1979 decimal(6, 4) NULL,
	Built1960_1969 int NULL,
	pctBuilt1960_1969 decimal(6, 4) NULL,
	Built1950_1959 int NULL,
	pctBuilt1950_1959 decimal(6, 4) NULL,
	Built1940_1949 int NULL,
	pctBuilt1940_1949 decimal(6, 4) NULL,
	BuiltBefore1940 int NULL,
	pctBuiltBefore1940 decimal(6, 4) NULL,
	MovedIn2010orLater int NULL,
	pctMovedIn2010orLater decimal(6, 4) NULL,
	MovedIn2000_2009 int NULL,
	pctMovedIn2000_2009 decimal(6, 4) NULL,
	MovedIn1990_1999 int NULL,
	pctMovedIn1990_1999 decimal(6, 4) NULL,
	MovedIn1980_1989 int NULL,
	pctMovedIn1980_1989 decimal(6, 4) NULL,
	MovedIn1970_1979 int NULL,
	pctMovedIn1970_1979 decimal(6, 4) NULL,
	MovedInBefore1969 int NULL,
	pctMovedInBefore1969 decimal(6, 4) NULL,
	NoVehicles int NULL,
	pctNoVehicles decimal(6, 4) NULL,
	Vehicles1 int NULL,
	pctVehicles1 decimal(6, 4) NULL,
	Vehicles2 int NULL,
	pctVehicles2 decimal(6, 4) NULL,
	VehiclesGE3 int NULL,
	pctVehiclesGE3 decimal(6, 4) NULL,
	HHFUtilGas int NULL,
	pctHHFUtilGas decimal(6, 4) NULL,
	HHFLPGas int NULL,
	pctHHFLPGas decimal(6, 4) NULL,
	HHFElectric int NULL,
	pctHHFElectric decimal(6, 4) NULL,
	HHFKerosene int NULL,
	pctHHFKerosene decimal(6, 4) NULL,
	HHFCoal int NULL,
	pctHHFCoal decimal(6, 4) NULL,
	HHFWood int NULL,
	pctHHFWood decimal(6, 4) NULL,
	HHFSolar int NULL,
	pctHHFSolar decimal(6, 4) NULL,
	HHFOther int NULL,
	pctHHFOther decimal(6, 4) NULL,
	HHFNoFuel int NULL,
	pctHHFNoFuel decimal(6, 4) NULL,
	NoPlumbing int NULL,
	pctNoPlumbing decimal(6, 4) NULL,
	NoKitchen int NULL,
	pctNoKitchen decimal(6, 4) NULL,
	NoPhone int NULL,
	pctNoPhone decimal(6, 4) NULL,
	PersonsPerRoomLow int NULL,
	pctPersonsPerRoomLow decimal(6, 4) NULL,
	PersonsPerRoomMedium int NULL,
	pctPersonsPerRoomMedium decimal(6, 4) NULL,
	PersonsPerRoomHigh int NULL,
	pctPersonsPerRoomHigh decimal(6, 4) NULL,
	HvalUnder50 int NULL,
	pctHvalUnder50 decimal(6, 4) NULL,
	Hval50 int NULL,
	pctHval50 decimal(6, 4) NULL,
	Hval100 int NULL,
	pctHval100 decimal(6, 4) NULL,
	Hval150 int NULL,
	pctHval150 decimal(6, 4) NULL,
	Hval200 int NULL,
	pctHval200 decimal(6, 4) NULL,
	Hval300 int NULL,
	pctHval300 decimal(6, 4) NULL,
	Hval500 int NULL,
	pctHval500 decimal(6, 4) NULL,
	HvalOverMillion int NULL,
	pctHvalOverMillion decimal(6, 4) NULL,
	MedianHValue money NULL,
	AvgHValue money NULL,
	HUsMort int NULL,
	pctHUsMort decimal(6, 4) NULL,
	HUsMortOver30Pct int NULL,
	pctHUsMortOver30Pct decimal(6, 4) NULL,
	MedianOwnerCostsMort money NULL,
	HUsNoMort int NULL,
	pctHUsNoMort decimal(6, 4) NULL,
	HUsNoMortOver30Pct int NULL,
	pctHUsNoMortOver30Pct decimal(6, 4) NULL,
	MedianOwnerCostsNoMort money NULL,
	CashRenter int NULL,
	pctCashRenter decimal(6, 4) NULL,
	NoCashRenter int NULL,
	pctNoCashRenter decimal(6, 4) NULL,
	MedianGrossRent money NULL,
	AvgGrossRent money NULL,
	CashRenterOver30Pct int NULL,
	pctCashRenterOver30Pct decimal(6, 4) NULL,
	CashRenterOver750 int NULL,
	pctCashRenterOver750 decimal(6, 4) NULL
);

SET @SQL = '
BULK INSERT SQLBook..ZipCensus
    FROM ''@LOADDIR\zipcensus_ss.txt''
	WITH (FIRSTROW = 2, FIELDTERMINATOR = ''	'')
';

SET @SQL = REPLACE(@SQL, '@LOADDIR', @LOADDIR)

EXEC(@SQL);





