---
title: "Lets_Project"
author: "Ruturaj himself"
date: "2023-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Maybe Project

Lets Roll (little disc about project will be here!)

```{r cars}
library(tidyverse)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
Hotel_Reservations <- read.csv("C:\\Users\\solan\\OneDrive\\Desktop\\Work\\St.Clair_sem_1\\DAB501_basic_stats\\DAB501\\Project\\Hotel_Reservations.csv", header=TRUE, stringsAsFactors=FALSE)
```

```{r}
ggplot(Hotel_Reservations) +
  stat_count(mapping = aes(x = room_type_reserved))
```

```{r}
ggplot(Hotel_Reservations) +
  stat_count(mapping = aes(x = type_of_meal_plan))
```

```{r}
ggplot(Hotel_Reservations) +
  stat_count(mapping = aes(x = market_segment_type))
```

```{r}
ggplot(Hotel_Reservations) +
  stat_count(mapping = aes(x = booking_status))
```

```{r}
ggplot(Hotel_Reservations) +
  stat_count(mapping = aes(x = no_of_adults))
```

```{r}
ggplot(Hotel_Reservations) +
  stat_count(mapping = aes(x = no_of_children)) +
  scale_x_continuous(breaks = seq(0, 10, by = 1))
```

```{r}
ggplot(Hotel_Reservations) +
  stat_count(mapping = aes(x = no_of_weekend_nights)) +
  scale_x_continuous(breaks = seq(0, 10, by = 1))
```

```{r}
ggplot(Hotel_Reservations) +
  stat_count(mapping = aes(x = no_of_week_nights)) +
  scale_x_continuous(breaks = seq(0, 10, by = 1))
```
aaaaNote that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
